apiVersion: v1
kind: Pod
metadata:
  name: netwatch
  namespace: infra
  annotations:
    vkube.io/network: gt
    vkube.io/image-policy: auto
    vkube.io/aliases: netwatch.gt.lo
spec:
  restartPolicy: Always
  containers:
    - name: netwatch
      image: registry.gt.lo:5000/netwatch:edge
      ports:
        - containerPort: 80
          protocol: TCP
        - containerPort: 9080
          protocol: TCP
        - containerPort: 22
          protocol: TCP
      livenessProbe:
        httpGet:
          path: /ui/
          port: 80
        periodSeconds: 30
        failureThreshold: 3
      volumeMounts:
        - name: data
          mountPath: /data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: netwatch-data
